/**
 * Creating a sidebar enables you to:
 'create an ordered group of docs
 'render a sidebar for each doc of that group
 'provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Deploy',
      items:[
        'deploy/docusaurus',
        'deploy/CICD持续集成',
        'deploy/Docker',
        'deploy/Docker部署静态文件',
        'deploy/VSCode同步文件到服务器',
        {
          type: 'doc',
          id: 'deploy/整合全栈Docker部署',
          label: '[实践]整合全栈Docker部署',
        },
      ]
    },
    {
      type: 'category',
      label: 'JavaScript',
      items:[
        'javascript/EventLoop',
        'javascript/Promise',
        'javascript/内存模型',
        'javascript/原型链',
        'javascript/数据类型',
        'javascript/时间处理',
        'javascript/设计模式',
        'javascript/路由',
      ]
    },
    {
      type: 'category',
      label: 'Vite',
      items:[
        'vite/create-vite和vite的区别',
        'vite/css模块化',
        'vite/react项目',
        'vite/resolve.alias原理',
        'vite/vite css配置',
        'vite/vite与webpack',
        'vite/vite加载静态资源',
        'vite/vite启动项目初体验',
        'vite/vite和ts的结合',
        'vite/vite性能优化概述',
        'vite/vite环境变量',
        'vite/vite的预加载',
        'vite/vite配置文件',
        'vite/为什么引入文件用path',
        'vite/什么是构建工具',
        'vite/手写vite-aliases插件',
        'vite/插件vite-plugin-html',
        'vite/插件vite-plugin-mock',
        'vite/插件原理窥探',
        'vite/构建优化',
        'vite/模拟vite开发服务器',
        'vite/跨域',
      ]
    },
    {
      type: 'category',
      label: 'Nest',
      items: [
        'nest/Controller',
        'nest/Middleware',
        'nest/Module',
        'nest/Node爬虫',
        'nest/Providers',
        'nest/Session',
        'nest/curd',
        'nest/nest使用mysql',
        'nest/nest前置',
        'nest/nest实体',
        'nest/swagger',
        'nest/初识nest',
        'nest/守卫',
        'nest/微信扫码登录二',
        'nest/微信登录一',
        'nest/拦截器',
        'nest/管道',
        'nest/自定义装饰器',
        'nest/鉴权',
        'nest/静态目录',
      ],
    },
    {
      type: 'category',
      label: 'CSS',
      items:[
        'css/垂直居中',
        'css/格式化上下文',
        'css/自适应',
      ]
    },
    // {
    //   type: 'category',
    //   label: '性能优化',
    //   items:[
    //     'performance/web性能指标',
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: 'React源码',
    //   items:[
    //     'source/Fiber',
    //     'source/jsx与createElement',
    //     'source/react源码架构',
    //     'source/react设计理念',
    //     'source/启动模式',
    //     'source/源码调试',
    //   ]
    // },
    // {
    //   type: 'category',
    //   label: '每日一题',
    //   items:[
    //     'exercises/part 1',
    //   ]
    // },
    {
      type: 'category',
      label: '版本控制',
      items:[
        'versioning/git',
      ]
    },
    {
      type: 'category',
      label: '工具',
      items:[
        'tools/VPN',
        'tools/mac环境',
        'tools/图床',
        'tools/常用软件',
      ]
    },
  ],
};

module.exports = sidebars;
